### ISSUE TITLE
Help! I am getting the following Error! 

### ISSUE THREAD

**Issue by tonini46** [Ejimba/pesapal#1]
I followed your configuration steps but i am getting the following error: Problem: parameter_absent | Advice: > oauth_parameters_absent | oauth_consumer_key

Please assist. Thanks in Advance

**Comment by Ejimba** [comment]
Hi,

The problem is due to consumer_key and consumer_secret missing from the config file. Please add your consumer key and consumer secret (that pesapal sent you when you signed up for a business account) to your config file found in

your_site/app/config/packages/ejimba/pesapal/config.php

if you cant locate the file above,

run the command

php artisan config:publish ejimba/pesapal

**Comment by tonini46** [comment]
Hey,
Thanks for getting back to me.
But I must be doing something wrong. I have the Consumer Key
and  Consumer Secret already configured.
Thanks.

**Comment by Ejimba** [comment]
You are welcome.
